stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\creditcard.csv
    deps:
    - .\data\raw\creditcard.csv
    - .\src\data\make_dataset.py
  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\
    deps:
    - .\src\models\train_model.py
    - .\data\processed\
    